### ISSUE TITLE
Must use Vaild fivemanage 

### ISSUE THREAD

**Issue by xdrahmahx** [Randolio/randol_imageui#1]
https://r2.fivemanage.com/VFB4iIOOimFkOxmeRnH49/Good.png is what i used and says invaild. is there a size limit or limited to file type?

**Comment by Randolio** [comment]
It uses the fivemanage public link which is https://r2.fivemanage.com/pub/

**Comment by Randolio** [comment]
I can shorten the string match to just https://r2.fivemanage.com to resolve future issues.

Change here: https://github.com/Randolio/randol_imageui/commit/e9239381902298c6c2aa67f02980bda7f8e58951
